"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { Activity, Bell, CalendarDays, CarFront, CheckCircle2, ClipboardCheck, FileText, Gauge, LayoutDashboard, Loader2, LogOut, Menu, PackageSearch, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, Trash2, Users, Wrench } from "lucide-react"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"

type Role = "admin" | "staff" | "mechanic" | "customer"
type Resource = "customers" | "vehicles" | "appointments" | "employees" | "repair-jobs" | "parts" | "estimates" | "invoices" | "notifications"
type RecordRow = Record<string, unknown> & { id: string }
type Session = { authenticated: boolean; identity?: { displayName: string; email: string }; account: null | { id: string; customerId?: string | null; fullName: string; email: string; role: Role }; canBootstrap: boolean; error?: string }
type Field = { key: string; label: string; type?: "text" | "email" | "number" | "date" | "datetime-local" | "textarea" | "select"; required?: boolean; options?: { value: string; label: string }[]; placeholder?: string }

const nav = [
  { id: "overview", label: "Overview", icon: LayoutDashboard, roles: ["admin", "staff", "mechanic", "customer"] },
  { id: "appointments", label: "Appointments", icon: CalendarDays, roles: ["admin", "staff", "mechanic", "customer"] },
  { id: "customers", label: "Customers", icon: Users, roles: ["admin", "staff"] },
  { id: "vehicles", label: "Vehicles", icon: CarFront, roles: ["admin", "staff", "customer"] },
  { id: "repair-jobs", label: "Repair jobs", icon: Wrench, roles: ["admin", "staff", "mechanic", "customer"] },
  { id: "employees", label: "Employees", icon: ShieldCheck, roles: ["admin"] },
  { id: "parts", label: "Inventory", icon: PackageSearch, roles: ["admin", "staff", "mechanic"] },
  { id: "estimates", label: "Estimates", icon: ClipboardCheck, roles: ["admin", "staff", "customer"] },
  { id: "invoices", label: "Invoices", icon: FileText, roles: ["admin", "staff", "customer"] },
  { id: "notifications", label: "Notifications", icon: Bell, roles: ["admin", "staff", "mechanic", "customer"] },
  { id: "reports", label: "Reports", icon: Activity, roles: ["admin", "staff"] },
] as const

const titles: Record<string, [string, string]> = {
  overview: ["Workshop overview", "Live operational snapshot"], appointments: ["Appointments", "Bookings, confirmations and workshop arrivals"],
  customers: ["Customers", "Contact information and linked workshop records"], vehicles: ["Vehicles", "Registered vehicles and service ownership"],
  "repair-jobs": ["Repair jobs", "Inspection-to-delivery job-card control"], employees: ["Employees", "Service advisors and mechanics"],
  parts: ["Parts inventory", "Pricing, stock and reorder thresholds"], estimates: ["Estimates", "Customer approval and repair authorization"],
  invoices: ["Invoices", "Repair billing and outstanding balances"], notifications: ["Notifications", "In-app and email delivery queue"],
  reports: ["Reports", "Revenue, workload and inventory intelligence"],
}

const columns: Record<Resource, { key: string; label: string }[]> = {
  customers: [{ key: "customerCode", label: "Code" }, { key: "fullName", label: "Customer" }, { key: "phone", label: "Phone" }, { key: "email", label: "Email" }, { key: "address", label: "Address" }],
  vehicles: [{ key: "registrationNumber", label: "Registration" }, { key: "vehicle", label: "Vehicle" }, { key: "customerName", label: "Customer" }, { key: "modelYear", label: "Year" }, { key: "currentMileage", label: "Mileage" }],
  appointments: [{ key: "appointmentNumber", label: "Booking" }, { key: "scheduledAt", label: "Scheduled" }, { key: "customerName", label: "Customer" }, { key: "vehicle", label: "Vehicle" }, { key: "complaint", label: "Request" }, { key: "status", label: "Status" }],
  employees: [{ key: "employeeCode", label: "Code" }, { key: "fullName", label: "Employee" }, { key: "role", label: "Role" }, { key: "designation", label: "Designation" }, { key: "specialization", label: "Specialization" }, { key: "status", label: "Status" }],
  "repair-jobs": [{ key: "jobNumber", label: "Job" }, { key: "vehicle", label: "Vehicle" }, { key: "customerName", label: "Customer" }, { key: "priority", label: "Priority" }, { key: "complaint", label: "Complaint" }, { key: "status", label: "Status" }],
  parts: [{ key: "sku", label: "SKU" }, { key: "name", label: "Part" }, { key: "brand", label: "Brand" }, { key: "stockOnHand", label: "Stock" }, { key: "reorderLevel", label: "Reorder" }, { key: "salePrice", label: "Sale price" }],
  estimates: [{ key: "estimateNumber", label: "Estimate" }, { key: "customerName", label: "Customer" }, { key: "subtotal", label: "Subtotal" }, { key: "discount", label: "Discount" }, { key: "total", label: "Total" }, { key: "status", label: "Status" }],
  invoices: [{ key: "invoiceNumber", label: "Invoice" }, { key: "jobNumber", label: "Job" }, { key: "customerName", label: "Customer" }, { key: "total", label: "Total" }, { key: "amountPaid", label: "Paid" }, { key: "balanceDue", label: "Balance" }, { key: "status", label: "Status" }],
  notifications: [{ key: "createdAt", label: "Created" }, { key: "channel", label: "Channel" }, { key: "title", label: "Title" }, { key: "message", label: "Message" }, { key: "status", label: "Status" }],
}

function format(value: unknown, key: string) {
  if (value === null || value === undefined || value === "") return "—"
  if (["total", "subtotal", "discount", "tax", "amountPaid", "balanceDue", "salePrice", "costPrice"].includes(key)) return `PKR ${Number(value).toLocaleString()}`
  if (["scheduledAt", "issuedAt", "createdAt", "promisedAt"].includes(key)) { const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString([], { dateStyle: "medium", timeStyle: key === "scheduledAt" ? "short" : undefined }) }
  return String(value).replaceAll("_", " ")
}

function statusBadge(value: unknown) {
  const text = format(value, "status"); const positive = ["ready", "paid", "active", "completed", "confirmed", "sent", "approved"].includes(String(value));
  return <Badge variant="outline" className={`rounded-md capitalize ${positive ? "border-emerald-200 bg-emerald-50 text-emerald-700" : ""}`}>{text}</Badge>
}

export function WorkshopDashboard() {
  const [session, setSession] = useState<Session | null>(null); const [active, setActive] = useState<string>("overview")
  const [summary, setSummary] = useState<Record<string, number>>({}); const [rows, setRows] = useState<RecordRow[]>([]); const [lookups, setLookups] = useState<Record<string, RecordRow[]>>({})
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [query, setQuery] = useState("")
  const [dialogOpen, setDialogOpen] = useState(false); const [editing, setEditing] = useState<RecordRow | null>(null); const [deleting, setDeleting] = useState<RecordRow | null>(null); const [form, setForm] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false)

  const loadSession = useCallback(async () => { const response = await fetch("/api/auth/session", { cache: "no-store" }); const data = await response.json(); setSession(data); setLoading(false) }, [])
  useEffect(() => { void loadSession() }, [loadSession])

  const loadSummary = useCallback(async () => { const response = await fetch("/api/workshop/summary", { cache: "no-store" }); if (response.ok) setSummary(await response.json()) }, [])
  const loadResource = useCallback(async (resource: Resource) => { setLoading(true); const response = await fetch(`/api/workshop/${resource}`, { cache: "no-store" }); const data = await response.json(); setRows(response.ok ? data.records ?? [] : []); if (!response.ok) setMessage(data.error ?? "Data could not be loaded"); setLoading(false) }, [])

  useEffect(() => {
    if (!session?.account) return
    if (active === "overview" || active === "reports") { void loadSummary(); setLoading(false) } else void loadResource(active as Resource)
  }, [active, session?.account, loadResource, loadSummary])

  useEffect(() => {
    if (!session?.account) return
    const keys = ["admin", "staff"].includes(session.account.role) ? ["customers", "vehicles", "employees"] : session.account.role === "customer" ? ["vehicles"] : []
    Promise.all(keys.map(async key => { const r = await fetch(`/api/workshop/${key}`); return [key, r.ok ? (await r.json()).records : []] as const })).then(entries => setLookups(Object.fromEntries(entries)))
  }, [session?.account])

  const role = session?.account?.role ?? "customer"
  const availableNav = nav.filter(item => (item.roles as readonly string[]).includes(role))
  const filteredRows = useMemo(() => !query ? rows : rows.filter(row => Object.values(row).some(value => String(value ?? "").toLowerCase().includes(query.toLowerCase()))), [rows, query])

  async function bootstrap() { setSaving(true); const response = await fetch("/api/auth/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "bootstrap" }) }); const data = await response.json(); setMessage(response.ok ? "Administrator account initialized" : data.error); await loadSession(); setSaving(false) }
  async function loadDemo() { setSaving(true); const response = await fetch("/api/workshop/demo", { method: "POST" }); const data = await response.json(); setMessage(response.ok ? data.message : data.error); await loadSummary(); const entries = await Promise.all(["customers", "vehicles", "employees"].map(async key => { const r = await fetch(`/api/workshop/${key}`); return [key, r.ok ? (await r.json()).records : []] as const })); setLookups(Object.fromEntries(entries)); setSaving(false) }

  function fieldsFor(resource: Resource): Field[] {
    const customerOptions = (lookups.customers ?? []).map(x => ({ value: String(x.id), label: `${x.fullName} · ${x.customerCode}` })); if (!customerOptions.length && role === "customer" && session?.account?.customerId) customerOptions.push({ value: session.account.customerId, label: "My customer account" }) ; const vehicleOptions = (lookups.vehicles ?? []).map(x => ({ value: String(x.id), label: `${x.registrationNumber} · ${x.vehicle ?? `${x.make} ${x.model}`}` })); const employeeOptions = (lookups.employees ?? []).filter(x => x.role === "staff").map(x => ({ value: String(x.id), label: `${x.fullName} · ${x.employeeCode}` }))
    const map: Record<Resource, Field[]> = {
      customers: [{ key: "fullName", label: "Full name", required: true }, { key: "email", label: "Email", type: "email" }, { key: "phone", label: "Phone", required: true }, { key: "address", label: "Address" }, { key: "notes", label: "Notes", type: "textarea" }],
      vehicles: [{ key: "customerId", label: "Customer", type: "select", options: customerOptions, required: true }, { key: "registrationNumber", label: "Registration number", required: true }, { key: "make", label: "Make", required: true }, { key: "model", label: "Model", required: true }, { key: "modelYear", label: "Model year", type: "number", required: true }, { key: "color", label: "Color" }, { key: "currentMileage", label: "Current mileage", type: "number", required: true }],
      appointments: [{ key: "customerId", label: "Customer", type: "select", options: customerOptions, required: true }, { key: "vehicleId", label: "Vehicle", type: "select", options: vehicleOptions, required: true }, { key: "scheduledAt", label: "Date and time", type: "datetime-local", required: true }, { key: "complaint", label: "Service request / complaint", type: "textarea", required: true }, { key: "status", label: "Status", type: "select", options: ["pending", "confirmed", "checked_in", "completed", "cancelled", "no_show"].map(x => ({ value: x, label: x.replaceAll("_", " ") })) }],
      employees: [{ key: "fullName", label: "Full name", required: true }, { key: "email", label: "Email", type: "email", required: true }, { key: "phone", label: "Phone", required: true }, { key: "role", label: "Role", type: "select", options: [{ value: "staff", label: "Service advisor / staff" }, { value: "mechanic", label: "Mechanic" }], required: true }, { key: "designation", label: "Designation", required: true }, { key: "specialization", label: "Specialization" }, { key: "hireDate", label: "Hire date", type: "date", required: true }, { key: "hourlyRate", label: "Hourly rate", type: "number", required: true }],
      "repair-jobs": [{ key: "customerId", label: "Customer", type: "select", options: customerOptions, required: true }, { key: "vehicleId", label: "Vehicle", type: "select", options: vehicleOptions, required: true }, { key: "serviceAdvisorId", label: "Service advisor", type: "select", options: employeeOptions, required: true }, { key: "complaint", label: "Complaint", type: "textarea", required: true }, { key: "diagnosis", label: "Diagnosis", type: "textarea" }, { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "urgent"].map(x => ({ value: x, label: x })) }, ...(editing ? [{ key: "status", label: "Move to next stage", type: "select" as const, options: ["inspection", "awaiting_approval", "approved", "in_repair", "on_hold", "quality_check", "ready", "delivered", "cancelled"].map(x => ({ value: x, label: x.replaceAll("_", " ") })) }] : []), { key: "promisedAt", label: "Promised delivery", type: "datetime-local" }],
      parts: [{ key: "sku", label: "SKU", required: true }, { key: "name", label: "Part name", required: true }, { key: "brand", label: "Brand" }, { key: "unit", label: "Unit", required: true }, { key: "costPrice", label: "Cost price", type: "number", required: true }, { key: "salePrice", label: "Sale price", type: "number", required: true }, { key: "stockOnHand", label: "Opening stock", type: "number", required: true }, { key: "reorderLevel", label: "Reorder level", type: "number", required: true }],
      estimates: [{ key: "inspectionId", label: "Inspection UUID", required: true }, { key: "customerId", label: "Customer", type: "select", options: customerOptions, required: true }, { key: "subtotal", label: "Subtotal", type: "number", required: true }, { key: "discount", label: "Discount", type: "number" }, { key: "tax", label: "Tax", type: "number" }, { key: "expiresAt", label: "Expiry date", type: "date" }],
      invoices: [{ key: "repairJobId", label: "Repair job UUID", required: true }, { key: "customerId", label: "Customer", type: "select", options: customerOptions, required: true }, { key: "subtotal", label: "Subtotal", type: "number", required: true }, { key: "discount", label: "Discount", type: "number" }, { key: "tax", label: "Tax", type: "number" }, { key: "amountPaid", label: "Amount paid", type: "number" }],
      notifications: [{ key: "userId", label: "Recipient user UUID", required: true }, { key: "channel", label: "Channel", type: "select", options: [{ value: "in_app", label: "In-app" }, { value: "email", label: "Email queue" }] }, { key: "type", label: "Type", required: true }, { key: "title", label: "Title", required: true }, { key: "message", label: "Message", type: "textarea", required: true }],
    }; return map[resource]
  }

  function openCreate() { setEditing(null); setForm({ status: active === "appointments" ? "pending" : "", priority: "normal", unit: "piece", discount: "0", tax: "0", amountPaid: "0" }); setDialogOpen(true) }
  function openEdit(row: RecordRow) { setEditing(row); setForm(Object.fromEntries(Object.entries(row).map(([k, v]) => [k, v === null ? "" : String(v)]))); setDialogOpen(true) }
  async function save() {
    const resource = active as Resource; setSaving(true); setMessage("")
    let payload: Record<string, string | number> = editing ? { ...form, id: editing.id } : form
    if (editing && resource === "repair-jobs" && form.status && form.status !== editing.status) {
      const statusResponse = await fetch(`/api/repair-jobs/${editing.id}/status`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: form.status, note: "Status updated from job-card workspace" }) }); const statusData = await statusResponse.json(); if (!statusResponse.ok) { setMessage(statusData.error ?? "Invalid workflow transition"); setSaving(false); return }
      const { status: _status, ...rest } = payload; payload = rest
    }
    const response = await fetch(`/api/workshop/${resource}`, { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json()
    setMessage(response.ok ? data.message : data.error ?? "Save failed"); setSaving(false); if (response.ok) { setDialogOpen(false); await loadResource(resource) }
  }
  async function remove() { if (!deleting) return; const resource = active as Resource; setSaving(true); const response = await fetch(`/api/workshop/${resource}?id=${deleting.id}`, { method: "DELETE" }); const data = await response.json(); setMessage(response.ok ? data.message : data.error); setDeleting(null); setSaving(false); if (response.ok) await loadResource(resource) }

  if (loading && !session) return <main className="grid min-h-screen place-items-center bg-background"><div className="text-center"><Loader2 className="mx-auto size-8 animate-spin text-primary" /><p className="mt-3 text-sm font-semibold text-muted-foreground">Securing workspace…</p></div></main>
  if (!session?.authenticated) return <main className="grid min-h-screen place-items-center p-5"><div className="panel max-w-md p-8 text-center"><ShieldCheck className="mx-auto size-10 text-primary" /><h1 className="mt-5 text-2xl font-black">Authentication required</h1><Button asChild className="mt-6 rounded-xl"><Link href="/sign-in">Go to sign in</Link></Button></div></main>
  if (!session.account) return <main className="grid min-h-screen place-items-center bg-background p-5"><div className="panel max-w-lg p-8"><Gauge className="size-10 text-primary" /><h1 className="mt-5 text-3xl font-black">{session.canBootstrap ? "Initialize AutoCare Pro" : "Complete customer registration"}</h1><p className="mt-3 leading-7 text-muted-foreground">{session.canBootstrap ? "No system administrator exists. Initialize the first protected Admin account with your verified identity." : "Your verified identity is not connected to a workshop profile yet."}</p>{session.canBootstrap ? <Button onClick={bootstrap} disabled={saving} className="mt-7 h-11 rounded-xl">{saving && <Loader2 className="animate-spin" />} Create first Admin account</Button> : <Button asChild className="mt-7 h-11 rounded-xl"><Link href="/sign-up">Complete registration</Link></Button>}{message && <p className="mt-4 text-sm font-semibold text-primary">{message}</p>}</div></main>

  const [title, subtitle] = titles[active]
  return <SidebarProvider><Sidebar collapsible="icon" className="border-r border-sidebar-border"><SidebarHeader className="border-b border-sidebar-border p-4"><Link href="/" className="flex items-center gap-3 overflow-hidden"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary text-white"><Wrench className="size-5" /></div><div className="min-w-0 group-data-[collapsible=icon]:hidden"><p className="truncate font-extrabold">AutoCare Pro</p><p className="truncate text-xs text-sidebar-foreground/55">Workshop workspace</p></div></Link></SidebarHeader><SidebarContent className="px-2 py-3"><SidebarGroup><SidebarGroupLabel>Workspace</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{availableNav.map(item => <SidebarMenuItem key={item.id}><SidebarMenuButton onClick={() => { setActive(item.id); setQuery(""); setMessage("") }} isActive={active === item.id} tooltip={item.label} className="h-10 rounded-xl px-3 data-[active=true]:bg-primary data-[active=true]:text-white"><item.icon className="size-[18px]" /><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter className="border-t border-sidebar-border p-3"><div className="flex items-center gap-3 rounded-xl bg-sidebar-accent p-2 group-data-[collapsible=icon]:hidden"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary text-sm font-black text-white">{session.account.fullName.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{session.account.fullName}</p><p className="truncate text-xs capitalize text-sidebar-foreground/55">{session.account.role}</p></div><a href="/signout-with-chatgpt?return_to=/" title="Sign out"><LogOut className="size-4" /></a></div></SidebarFooter></Sidebar>
    <SidebarInset><header className="sticky top-0 z-20 flex min-h-17 items-center justify-between gap-3 border-b border-border bg-background/90 px-4 py-3 backdrop-blur-xl md:px-7"><div className="flex min-w-0 items-center gap-3"><SidebarTrigger className="rounded-lg md:hidden"><Menu /></SidebarTrigger><div className="min-w-0"><h1 className="truncate text-lg font-black tracking-tight md:text-xl">{title}</h1><p className="truncate text-sm text-muted-foreground">{subtitle}</p></div></div><div className="flex items-center gap-2"><Button variant="outline" size="icon" className="rounded-xl" onClick={() => active === "overview" ? loadSummary() : active !== "reports" && loadResource(active as Resource)}><RefreshCw className="size-4" /></Button>{!(["overview","reports"].includes(active)) && !(["mechanic","customer"].includes(role) && !["vehicles","appointments"].includes(active)) && <Button onClick={openCreate} className="rounded-xl"><Plus className="size-4" /><span className="hidden sm:inline">Add new</span></Button>}</div></header>
      <main className="min-w-0 flex-1 bg-background p-4 md:p-7">{message && <div className="mb-5 flex items-center justify-between rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm font-semibold text-primary"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}{active === "overview" ? <Overview summary={summary} role={role} setActive={setActive} /> : active === "reports" ? <Reports summary={summary} /> : <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div className="relative min-w-[220px] flex-1 sm:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`} className="h-10 rounded-xl pl-9" /></div><p className="text-sm font-semibold text-muted-foreground">{filteredRows.length} records</p></div><div className="overflow-x-auto">{loading ? <div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : filteredRows.length === 0 ? <div className="grid min-h-72 place-items-center p-8 text-center"><div><ClipboardCheck className="mx-auto size-10 text-muted-foreground/40" /><h3 className="mt-4 font-bold">No records found</h3><p className="mt-1 text-sm text-muted-foreground">Create the first record or adjust your search.</p></div></div> : <Table><TableHeader><TableRow>{columns[active as Resource].map(col=><TableHead key={col.key}>{col.label}</TableHead>)}{["admin","staff"].includes(role) && <TableHead className="text-right">Actions</TableHead>}</TableRow></TableHeader><TableBody>{filteredRows.map(row=><TableRow key={row.id}>{columns[active as Resource].map(col=><TableCell key={col.key} className={col.key === "complaint" || col.key === "message" ? "max-w-64 truncate" : "whitespace-nowrap"}>{col.key === "status" || col.key === "priority" || col.key === "channel" ? statusBadge(row[col.key]) : format(row[col.key], col.key)}</TableCell>)}{["admin","staff"].includes(role) && <TableCell><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" onClick={()=>openEdit(row)} className="rounded-lg"><Pencil className="size-4" /></Button>{role === "admin" && <Button variant="ghost" size="icon" onClick={()=>setDeleting(row)} className="rounded-lg text-destructive"><Trash2 className="size-4" /></Button>}</div></TableCell>}</TableRow>)}</TableBody></Table>}</div></section>}</main>
    </SidebarInset>

    {!(["overview","reports"].includes(active)) && <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editing ? "Edit" : "Add"} {titles[active][0]}</DialogTitle><DialogDescription>Fields are validated again by the server before saving.</DialogDescription></DialogHeader><div className="grid gap-5 py-2 sm:grid-cols-2">{fieldsFor(active as Resource).map(field => <div key={field.key} className={field.type === "textarea" ? "space-y-2 sm:col-span-2" : "space-y-2"}><Label htmlFor={field.key}>{field.label}{field.required && " *"}</Label>{field.type === "textarea" ? <Textarea id={field.key} value={form[field.key] ?? ""} onChange={e=>setForm({...form,[field.key]:e.target.value})} className="min-h-24 rounded-xl" /> : field.type === "select" ? <Select value={form[field.key] ?? ""} onValueChange={value=>setForm({...form,[field.key]:value})}><SelectTrigger className="w-full rounded-xl"><SelectValue placeholder={`Select ${field.label.toLowerCase()}`} /></SelectTrigger><SelectContent>{field.options?.map(option=><SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select> : <Input id={field.key} type={field.type ?? "text"} value={form[field.key] ?? ""} onChange={e=>setForm({...form,[field.key]:e.target.value})} required={field.required} placeholder={field.placeholder} className="h-10 rounded-xl" />}</div>)}</div><DialogFooter><Button variant="outline" onClick={()=>setDialogOpen(false)} className="rounded-xl">Cancel</Button><Button onClick={save} disabled={saving} className="rounded-xl">{saving && <Loader2 className="animate-spin" />} Save record</Button></DialogFooter></DialogContent></Dialog>}
    <AlertDialog open={!!deleting} onOpenChange={open=>!open&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this record?</AlertDialogTitle><AlertDialogDescription>This action is blocked automatically when the record is linked to protected workshop history.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={remove} className="bg-destructive text-white">Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </SidebarProvider>
}

function Overview({ summary, role, setActive }: { summary: Record<string, number>; role: Role; setActive: (value: string) => void }) {
  const metrics = [{ label: "Active repair jobs", value: summary.activeJobs ?? 0, icon: Wrench, tone: "bg-orange-500/10 text-orange-600", target: "repair-jobs" }, { label: "Today’s appointments", value: summary.todaysAppointments ?? 0, icon: CalendarDays, tone: "bg-sky-500/10 text-sky-600", target: "appointments" }, { label: "Ready for delivery", value: summary.readyForDelivery ?? 0, icon: CheckCircle2, tone: "bg-emerald-500/10 text-emerald-600", target: "repair-jobs" }, { label: "Low-stock parts", value: summary.lowStock ?? 0, icon: PackageSearch, tone: "bg-amber-500/10 text-amber-600", target: "parts" }]
  return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.filter(x=>role!=="customer"||x.target!=="parts").map(({label,value,icon:Icon,tone,target})=><button key={label} onClick={()=>setActive(target)} className="metric-card text-left"><div className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></div><p className="mt-5 text-3xl font-black">{value}</p><p className="mt-1 text-sm font-semibold text-muted-foreground">{label}</p></button>)}</section><section className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><article className="panel p-6"><div className="flex justify-between"><div><h2 className="font-black">Workshop control center</h2><p className="mt-1 text-sm text-muted-foreground">Every stage is connected to the same vehicle record.</p></div><Gauge className="text-primary" /></div><div className="mt-7 grid gap-3 sm:grid-cols-5">{[["Inspection",22],["Approval",38],["Repair",68],["Quality check",84],["Ready",100]].map(([label,value],i)=><div key={label as string}><div className={`h-2 rounded-full ${i<3?"bg-primary":"bg-emerald-500"}`} /><p className="mt-3 text-sm font-bold">{label}</p><p className="mt-1 text-xs text-muted-foreground">Stage {i+1}</p></div>)}</div></article><article className="panel p-6"><h2 className="font-black">System records</h2><div className="mt-5 space-y-4"><div className="flex justify-between"><span className="text-sm text-muted-foreground">Customers</span><b>{summary.customers ?? 0}</b></div><div className="flex justify-between"><span className="text-sm text-muted-foreground">Registered vehicles</span><b>{summary.vehicles ?? 0}</b></div><div className="flex justify-between"><span className="text-sm text-muted-foreground">Collected revenue</span><b>PKR {(summary.collectedRevenue ?? 0).toLocaleString()}</b></div></div></article></section></>
}

function Reports({ summary }: { summary: Record<string, number> }) {
  const revenue = summary.collectedRevenue ?? 0
  return <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="panel p-6"><div className="flex items-center justify-between"><div><h2 className="font-black">Workshop performance</h2><p className="mt-1 text-sm text-muted-foreground">Current database totals</p></div><Activity className="text-primary" /></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-muted p-5"><p className="text-sm text-muted-foreground">Collected</p><p className="mt-2 text-2xl font-black">PKR {revenue.toLocaleString()}</p></div><div className="rounded-2xl bg-muted p-5"><p className="text-sm text-muted-foreground">Customers</p><p className="mt-2 text-2xl font-black">{summary.customers ?? 0}</p></div><div className="rounded-2xl bg-muted p-5"><p className="text-sm text-muted-foreground">Vehicles</p><p className="mt-2 text-2xl font-black">{summary.vehicles ?? 0}</p></div></div><div className="mt-8 space-y-5">{[["Active workload",summary.activeJobs??0,70],["Today’s bookings",summary.todaysAppointments??0,45],["Ready for delivery",summary.readyForDelivery??0,28]].map(([label,value,progress])=><div key={label as string}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{label}</span><b>{value}</b></div><Progress value={progress as number} /></div>)}</div></article><article className="panel p-6"><h2 className="font-black">Report integrity</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Figures are calculated from live workshop records. No fabricated performance percentages or hard-coded revenue are used.</p><div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><CheckCircle2 className="mb-3 size-5" />Live database aggregation enabled</div></article></section>
}
